management:
  endpoints:
    web:
      exposure:
        include: "*"
    expose: "*"
    shutdown:
      enabled: "true"
  trace.http.enabled: true
  server:
    port: 8081

spring:
  datasource:
    url: postgres://vugqnxhrdnkftz:d0f42d4c7596d75629e391a059468988282aa83d4b4a203866a4dc4b3cb56d1e@ec2-3-248-121-12.eu-west-1.compute.amazonaws.com:5432/da1pc9bkqq4cvf
    username: vugqnxhrdnkftz
    password: d0f42d4c7596d75629e391a059468988282aa83d4b4a203866a4dc4b3cb56d1e
    driver-class-name: org.postgresql.Driver
  ## Specify DBMS
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.kinart.stock.business.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

flickr:
  apiKey: da3d406c77a919c3f7b0d5f22f0fefb1
  apiSecret: 586bedcf752a71c8
  appKey: 72157720837293999-64c1ecc4e4e04542
  appSecret: bec0945d201abfa3
