DELETE FROM PARAMDATA;
DELETE FROM PARAMTABLE;
DELETE FROM PARAMCOLUMN;
DELETE FROM CALENDRIERPAIE;
DELETE FROM VIREMENTSALARIE;
INSERT INTO PARAMDATA (ID, IDENTREPRISE, CTAB, CACC, NUME, VALL, VALM, VALT, DUTI, LAST_MODIFIED_DATE, VALD, CREATION_DATE) SELECT HIBERNATE_SEQUENCE.nextval, 1, CTAB, CACC, NUME, VALL, VALM, VALT, DUTI, DDMO, VALD, '01/01/2023' FROM RHFNOM e WHERE CDOS='02';
INSERT INTO PARAMTABLE (ID, IDENTREPRISE, CTAB, LIBE, NCCL, TYPC, DUTI, LAST_MODIFIED_DATE, PROFIL, CREATION_DATE) SELECT HIBERNATE_SEQUENCE.nextval, 1, CTAB, LIBE, NCCL, TYPC, DUTI, DDMO, PROFIL, '01/01/2023' FROM RHTNOM e WHERE CDOS='02';
INSERT INTO PARAMCOLUMN (ID, IDENTREPRISE, CTAB, CTYP, NUME, LIBE, DUTI, LAST_MODIFIED_DATE, NUME_LIEN, CTAB_LIEN, CODE_PROFIL, CTYP_LIEN, OBLIGATOIRE, CREATION_DATE) SELECT HIBERNATE_SEQUENCE.nextval, 1, CTAB, CTYP, NUME, LIBE, DUTI, DDMO, NUME_LIEN, CTAB_LIEN, CODE_PROFIL, CTYP_LIEN, OBLIGATOIRE, '01/01/2023' FROM RHLNOM e WHERE CDOS='02';
INSERT INTO CALENDRIERPAIE (ID, IDENTREPRISE, JOUR, JSEM, OUVR, FER, NSEM, ANNE, TRAV, LAST_MODIFIED_DATE, CREATION_DATE) SELECT HIBERNATE_SEQUENCE.nextval, 1, JOUR, JSEM, OUVR, FER, NSEM, ANNE, TRAV, '01/01/2023', '01/01/2023' FROM RHPCALENDRIER e WHERE CDOS='15';
INSERT INTO VIREMENTSALARIE (ID, IDENTREPRISE, NMAT, NLIG, BQAG, GUIC, COMP, CLE, BQSO, POURC, MONT, DVD, TXCHG, MNTDB, MNTDVD, AAMM, PRINC, SWIFT, TITU, LAST_MODIFIED_DATE, CREATION_DATE) SELECT HIBERNATE_SEQUENCE.nextval, 1, NMAT, NLIG, BQAG, GUIC, COMP, CLE, BQSO, POURC, MONT, DVD, TXCHG, MNTDB, MNTDVD, AAMM, PRINC, SWIFT, TITU, '01/01/2023', '01/01/2023' FROM RHTVRMTAGENT e WHERE CDOS='02';
INSERT INTO DOSSIERPAIE (ID, IDENTREPRISE, NRED, DRSC, DAD1, DAD2, DAD3, DAD4, DCPO, DBDI, DPAY, DNRC, DTST, DNST, DNCP, DDEX, DFEX, DDES, DFES, DCJR, DDEV, DCAN, DNPE, DUEB, DDPA, DNSA, DDCD, NDDD, DMPA, NPCE, CARR, GCLI, GFOU, RAPP, MAJI, NBJV, NTMP, TMMP, SERVEUR, PORT, UTILISATEUR, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, NRED, DRSC, DAD1, DAD2, DAD3, DAD4, DCPO, DBDI, DPAY, DNRC, DTST, DNST, DNCP, DDEX, DFEX, DDES, DFES, DCJR, DDEV, DCAN, DNPE, DUEB, DDPA, DNSA, DDCD, NDDD, DMPA, NPCE, CARR, GCLI, GFOU, RAPP, MAJI, NBJV, NTMP, TMMP, SERVEUR, PORT, UTILISATEUR, '01/01/2023', '01/01/2023' FROM CPDOS e WHERE CDOS='02';
INSERT INTO ELEMENTFIXESALAIRE (ID, IDENTREPRISE, NMAT, CODP, MONP, DDEB, DFIN, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, NMAT, CODP, MONP, DDEB, DFIN, '01/01/2023', '01/01/2023' FROM rhteltfixagent e WHERE CDOS='02';
INSERT INTO ELEMENTSALAIRE (ID, IDENTREPRISE, CRUB, LRUB, CALC, PROR, PPCG, PRAC, PRHR, PRTB, PRCL, PRTM, PRNO, PPAS, MOI1, MOI2, MOI3, MOI4, BUL1, BUL2, BUL3, BUL4, APCF, CABF, PRBUL, CBULF, EDNUL, EDCUM, EDBBU, EPBUL, AJUS, AJNU, SNET, ECAR, TYPR, ESAT, RREG, RMAN, PERC, FREQ, ADDF, RCON, EDDF, BASC, TRTC, TRVE, EXO, VAL1, VAL2, VAL3, MOPA, LBTM, OPFI, ALGO, CLE1, CLE2, TABL, TOUM, NUTM, ARRO, RESL, SUP1, SUPS, SUP2, INF1, INFS, INF2, EGU1, EGUS, EGU2, CS1, CS2, CS3, SEXE, AGE1, AGE2, SIT1, SIT2, SIT3, SIT4, NBE1, NBE2, NAT1, NAT2, ZCA1, ZCA2, ZCA3, ZCA4, CAT1, CAT2, TYC1, TYC2, TYC3, TYC4, TYC5, TYC6, TYC7, TYC8, GRA1, GRA2, GRA3, GRA4, GRA5, GRA6, GRA7, GRA8, AVN, NIV11, NIV12, NIV13, NIV14, NIV21, NIV22, NIV23, NIV24, NIV31, NIV32, NIV33, NIV34, SYND, REG1, REG2, REG3, REG4, REG5, REG6, REG7, REG8, CLAS1, CLAS2, CLAS3, CLAS4, CFON, HIF1, HIF2, HIF3, HIF4, FON1, FON2, FON3, FON4, FON5, FON6, FON7, FON8, ZL11, ZL12, ZL21, ZL22, CAIS, DNBP, TXMT, TRCU, BASP, ABAT, ABMX, PMIN, PMAX, PCAB, PDAP, COMP, CPER, DE01, DE02, DE03, DE04, DE05, DE06, DE07, DE08, DE09, DE10, DE11, DE12, DE13, DE14, DE15, DE16, DE17, DE18, DE19, DE20, CR01, CR02, CR03, CR04, CR05, FBAS, TBAS, NOTE, FORMULE, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, CRUB, LRUB, CALC, PROR, PPCG, PRAC, PRHR, PRTB, PRCL, PRTM, PRNO, PPAS, MOI1, MOI2, MOI3, MOI4, BUL1, BUL2, BUL3, BUL4, APCF, CABF, PRBUL, CBULF, EDNUL, EDCUM, EDBBU, EPBUL, AJUS, AJNU, SNET, ECAR, TYPR, ESAT, RREG, RMAN, PERC, FREQ, ADDF, RCON, EDDF, BASC, TRTC, TRVE, EXO, VAL1, VAL2, VAL3, MOPA, LBTM, OPFI, ALGO, CLE1, CLE2, TABL, TOUM, NUTM, ARRO, RESL, SUP1, SUPS, SUP2, INF1, INFS, INF2, EGU1, EGUS, EGU2, CS1, CS2, CS3, SEXE, AGE1, AGE2, SIT1, SIT2, SIT3, SIT4, NBE1, NBE2, NAT1, NAT2, ZCA1, ZCA2, ZCA3, ZCA4, CAT1, CAT2, TYC1, TYC2, TYC3, TYC4, TYC5, TYC6, TYC7, TYC8, GRA1, GRA2, GRA3, GRA4, GRA5, GRA6, GRA7, GRA8, AVN, NIV11, NIV12, NIV13, NIV14, NIV21, NIV22, NIV23, NIV24, NIV31, NIV32, NIV33, NIV34, SYND, REG1, REG2, REG3, REG4, REG5, REG6, REG7, REG8, CLAS1, CLAS2, CLAS3, CLAS4, CFON, HIF1, HIF2, HIF3, HIF4, FON1, FON2, FON3, FON4, FON5, FON6, FON7, FON8, ZL11, ZL12, ZL21, ZL22, CAIS, DNBP, TXMT, TRCU, BASP, ABAT, ABMX, PMIN, PMAX, PCAB, PDAP, COMP, CPER, DE01, DE02, DE03, DE04, DE05, DE06, DE07, DE08, DE09, DE10, DE11, DE12, DE13, DE14, DE15, DE16, DE17, DE18, DE19, DE20, CR01, CR02, CR03, CR04, CR05, FBAS, TBAS, NOTE, FORMULE, '01/01/2023', '01/01/2023' FROM rhprubrique e WHERE CDOS='02';
INSERT INTO ELEMENTSALAIREBASE (ID, IDENTREPRISE, CRUB, NUME, SIGN, RUBK, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, CRUB, NUME, SIGN, RUBK, '01/01/2023', '01/01/2023' FROM rhprubriquebase e WHERE CDOS='02';
INSERT INTO ELEMENTSALAIREBAREME (ID, IDENTREPRISE, CRUB, NUME, VAL1, VAL2, TAUX, MONT, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, CRUB, NUME, VAL1, VAL2, TAUX, MONT, '01/01/2023', '01/01/2023' FROM rhprubriquebareme e WHERE CDOS='02';
INSERT INTO SALARIE (ID, IDENTREPRISE, NMAT, NIV1, NIV2, NIV3, CALS, CLAS, NOM, PREN, SEXE, DTNA, NATO, SITF, NBCJ, NBEF, NBEC, NBFE, NBPT, MODP, BANQ, GUIC, COMP, CLE, CCPT, BQSO, VILD, CAT, ECH, GRAD, FONC, AFEC, CODF, INDI, CTAT, TINP, SYND, HIFO, ZLI1, ZLI2, DTES, DDCA, TYPC, AVN1, AVN2, AVN3, AVN4, AVN5, AVN6, AVN7, REGI, ZRES, DMST, NPIE, MRRX, DMRR, MTFR, LIEU, CODS, PNET, SNET, DEVP, EQUI, DELS, TITS, DTIT, DEPR, DECC, JAPA, DAPA, JAPEC, DAPEC, JDED, DDED, JRLA, JRLEC, NBJCF, NBJAF, DDCF, DFCF, MTCF, PMCF, NBJSE, NBJSA, NMJF, ADR1, ADR2, ADR3, ADR4, BPOS, NTEL, PNAI, COMM, PBPE, DCHG, MCHG, DFES, STOR, NBJTR, DRTCG, DDENV, DRENV, NOSS, CONT, NBJSM, SANA, TYFO1, TYFO2, NIFO, DCHF, NOTE, CODEPOSTE, CODESITE, ZLI3, ZLI4, ZLI5, ZLI6, ZLI7, ZLI8, ZLI9, ZLI10, LNAI, LEMB, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, NMAT, NIV1, NIV2, NIV3, CALS, CLAS, NOM, PREN, SEXE, DTNA, NATO, SITF, NBCJ, NBEF, NBEC, NBFE, NBPT, MODP, BANQ, GUIC, COMP, CLE, CCPT, BQSO, VILD, CAT, ECH, GRAD, FONC, AFEC, CODF, INDI, CTAT, TINP, SYND, HIFO, ZLI1, ZLI2, DTES, DDCA, TYPC, AVN1, AVN2, AVN3, AVN4, AVN5, AVN6, AVN7, REGI, ZRES, DMST, NPIE, MRRX, DMRR, MTFR, LIEU, CODS, PNET, SNET, DEVP, EQUI, DELS, TITS, DTIT, DEPR, DECC, JAPA, DAPA, JAPEC, DAPEC, JDED, DDED, JRLA, JRLEC, NBJCF, NBJAF, DDCF, DFCF, MTCF, PMCF, NBJSE, NBJSA, NMJF, ADR1, ADR2, ADR3, ADR4, BPOS, NTEL, PNAI, COMM, PBPE, DCHG, MCHG, DFES, STOR, NBJTR, DRTCG, DDENV, DRENV, NOSS, CONT, NBJSM, SANA, TYFO1, TYFO2, NIFO, DCHF, NOTE, CODEPOSTE, CODESITE, ZLI3, ZLI4, ZLI5, ZLI6, ZLI7, ZLI8, ZLI9, ZLI10, LNAI, LEMB, '01/01/2023', '01/01/2023'
FROM RHPAGENT e WHERE CDOS='02';
INSERT INTO CUMULPAIE (ID, IDENTREPRISE, NMAT, AAMM, RUBQ, NBUL, BASC, BASP, TAUX, MONT, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, NMAT, AAMM, RUBQ, NBUL, BASC, BASP, TAUX, MONT, '01/01/2023', '01/01/2023' FROM RHTCUMUL e WHERE CDOS='02';
INSERT INTO HistoCalculPaie (ID, IDENTREPRISE, NMAT, AAMM, RUBQ, NBUL, BASC, BASP, TAUX, MONT, LAST_MODIFIED_DATE, CREATION_DATE)
SELECT HIBERNATE_SEQUENCE.nextval, 1, NMAT, AAMM, RUBQ, NBUL, BASC, BASP, TAUX, MONT, '01/01/2023', '01/01/2023' FROM RHTCUMUL e WHERE CDOS='02';

INSERT INTO ENTREPRISE (ID, CREATION_DATE, LAST_MODIFIED_DATE, ADRESSE1, ADRESSE2, CODEPOSTALE, PAYS, VILLE, CODEFISCAL, DESCRIPTION, EMAIL, NOM, NUMTEL, PHOTO, SITEWEB) VALUES (1, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'Niamey', 'Niamey', '11450', 'Niger', 'Niamey', '11111111', null, 'cyrille@yahoo.com', 'CYRILLE MBASSI', '8194617460', null, null);
INSERT INTO UTILISATEUR (ID, CREATION_DATE, LAST_MODIFIED_DATE, ADRESSE1, ADRESSE2, CODEPOSTALE, PAYS, VILLE, CLANG, DATEDENAISSANCE, EMAIL, MOTDEPASSE, NOM, PHOTO, PRENOM, IDENTREPRISE, VALID1, VALID2, VALID3, VALID4) VALUES (1, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'Niger', 'Niger', '11450', 'Niger', 'Niger', '001', null, 'cyrille@yahoo.com', '12345', 'MBASSI MASSOUKE', null, 'CYRILLE', 1, null, null, null, null);

INSERT INTO ROLES (ID, CREATION_DATE, LAST_MODIFIED_DATE, ACTIF, DATE_DEB, DATE_FIN, DROIT, MODULE, ROLENAME, IDUTILISATEUR) VALUES (1, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'O', TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2025-01-01 00:00:00', null, null, 'DRHL', 1);

INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (21, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'VAL_DH', 99, 'DELT', 1, 1, null, 'cyrille.mbassi@yahoo.com', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (22, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'VAL_SCE', 99, 'DELT', 1, 1, null, 'cyrille.mbassi@yahoo.com', null, null);

INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (8, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ANN_HABIL', 99, 'DELT', 1, 1, null, 'Bonjour,

La demande d''habilitation numéro $NUMERO de $SENDER a été annulée par ce dernier.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (12, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ANN_ATTEST', 99, 'DELT', 1, 1, null, 'Bonjour,

La demande d''attestation numéro $NUMERO de $SENDER a été annulée par ce dernier.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (13, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ANN_MODINF', 99, 'DELT', 1, 1, null, 'Bonjour,

La demande de modification d''information numéro $NUMERO de $SENDER a été annulée par ce dernier.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (20, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ANN_PRET', 99, 'DELT', 1, 1, null, 'Bonjour,

La demande de prêt numéro $NUMERO de $SENDER a été annulée par ce dernier.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (5, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ANN_ABSCGE', 99, 'DELT', 1, 1, null, 'Bonjour,

La demande d''absence / congé numéro $NUMERO de $SENDER a été annulée par ce dernier.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (1, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'MOD_ABSCGE', 99, 'DELT', 1, 1, null, 'Bonjour,

Merci de bien vouloir traiter la demande d''absence / congé numéro $NUMERO de $SENDER du $DATEDEBUT au $DATEFIN.

Cdlt,

RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (9, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'MOD_ATTEST', 99, 'DELT', 1, 1, null, 'Bonjour,

Merci de bien vouloir traiter la demande d''attestation numéro $NUMERO de $SENDER.

Cdlt,

RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (16, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'MOD_MODINF', 99, 'DELT', 1, 1, null, 'Bonjour,

Merci de traiter la demande de modification de l''information de la fiche salarié numéro $NUMERO de $SENDER.

Cordialement,

RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (17, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'MOD_PRET', 99, 'DELT', 1, 1, null, 'Bonjour,

Merci de traiter la demande de prêt numéro $NUMERO de $SENDER.

Cordialement,

RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (2, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'MOD_HABIL', 99, 'DELT', 1, 1, null, 'Bonjour,

Merci de traiter la demande d''habilitation numéro $NUMERO de $SENDER.

Cordialement,

RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (7, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'REJ_HABIL', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''habilitation numéro $NUMERO du $DATE a été rejetée.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (11, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'REJ_ATTEST', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''attestation numéro $NUMERO du $DATE a été rejetée.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (14, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'REJ_MODINF', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande de modification de l''information numéro $NUMERO du $DATE de la fiche salarié a été rejetée.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (19, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'REJ_PRET', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande de prêt numéro $NUMERO du $DATE a été rejetée.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (4, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'REJ_ABSCGE', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''absence / congé numéro $NUMERO pour la période du $DATEDEBUT au $DATEFIN a été rejetée.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (6, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ACK_HABIL', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''habilitation numéro $NUMERO a été validée par $VALIDATOR.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (10, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ACK_ATTEST', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''attestation numéro $NUMERO a été validée par $VALIDATOR.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (15, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ACK_MODINF', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande de modification de l''information de la fiche salarié numéro $NUMERO a été validée par $VALIDATOR.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (18, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ACK_PRET', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande de prêt numéro $NUMERO a été validée par $VALIDATOR.

Cdlt,
RH SONIBANK', null, null);
INSERT INTO PARAMDATA (ID, CREATION_DATE, LAST_MODIFIED_DATE, CACC, CTAB, DUTI, IDENTREPRISE, NUME, VALD, VALL, VALM, VALT) VALUES (3, TIMESTAMP '2023-01-01 00:00:00', TIMESTAMP '2023-01-01 00:00:00', 'ACK_ABSCGE', 99, 'DELT', 1, 1, null, 'Bonjour,

Votre demande d''absence / congé numéro $NUMERO a été validée par $VALIDATOR.

Cdlt,
RH SONIBANK', null, null);


