management:
  endpoints:
    web:
      exposure:
        include: "*"
    expose: "*"
    shutdown:
      enabled: "true"
  trace.http.enabled: true
  server:
    port: 8088

  #jasypt:
    #encryptor:
    #password: megatimgroupe

spring:
  #mvc:
  #pathmatch:
  #matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:amplituderh   #jdbc:mysql://localhost:3306/portal_notification jdbc:oracle:thin:@localhost:1521:amplituderh 192.168.1.88:1521:sopra
    username: delta   # delta PORTAILDB
    password: delta  #ENC(FsSQiV5g7h53d9FwuaGf+Q==  delta PORTAILDB
    driver-class-name: oracle.jdbc.OracleDriver    #com.mysql.cj.jdbc.Driver
  mail:
    host: 192.168.160.65 #SMTP server address smtp.gmail.com 192.168.160.65
    port: 25 #Port  465 25
    username: amplituderh@sonibank.com #Login account lohanlaurel@gmail.com  amplituderh@sonibank.com
    password: sabc #Login password (or authorization code)  qszduiavxyicburp  sabc
    properties:
      from: DRH.SONIBANKNiger@sonibank.com #Email sender (i.e. real email)  sirh@megatim.com
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: false
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000
          ssl:
            enable: false  # true false
  ## Specify DBMS
  jpa:
    database: ORACLE #MYSQL
    show-sql: true
    properties:
      hibernate:
        # format_sql: true
        allow_update_outside_transaction: true
        session_factory:
          interceptor: com.kinart.stock.business.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.OracleDialect #org.hibernate.dialect.MySQL8Dialect
  #logging:
    #level:
      #org:
        #hibernate:
      #type: trace

server:
  port: 8088
  servlet:
      context-path: /gestiondestock

flickr:
  apiKey: da3d406c77a919c3f7b0d5f22f0fefb1
  apiSecret: 586bedcf752a71c8
  appKey: 72157720837293999-64c1ecc4e4e04542
  appSecret: bec0945d201abfa3

