management:
  endpoints:
    web:
      exposure:
        include: "*"
    expose: "*"
    shutdown:
      enabled: "true"
  trace.http.enabled: true
  server:
    port: 8081

  #jasypt:
    #encryptor:
    #password: megatimgroupe

spring:
  #mvc:
  #pathmatch:
  #matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:amplituderh   #jdbc:mysql://localhost:3306/portal_notification
    username: delta
    password: delta  #ENC(FsSQiV5g7h53d9FwuaGf+Q==)
    driver-class-name: oracle.jdbc.OracleDriver    #com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com #SMTP server address
    port: 465
    username: lohanlaurel@gmail.com #Login account
    password: qszduiavxyicburp #Login password (or authorization code)
    properties:
      from: sirh@megatim.com #Email sender (i.e. real email)
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 20000
          timeout: 20000
          writetimeout: 20000
          ssl:
            enable: true
  ## Specify DBMS
  jpa:
    database: ORACLE #MYSQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        allow_update_outside_transaction: true
        session_factory:
          interceptor: com.kinart.stock.business.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.OracleDialect #org.hibernate.dialect.MySQL8Dialect
  #logging:
    #level:
      #org:
        #hibernate:
      #type: trace

server:
  port: 8081

flickr:
  apiKey: da3d406c77a919c3f7b0d5f22f0fefb1
  apiSecret: 586bedcf752a71c8
  appKey: 72157720837293999-64c1ecc4e4e04542
  appSecret: bec0945d201abfa3

