spring:
  datasource:
    url: postgres://jdlysksngpmstg:def7148466dd0f8b1bb5b50844542a7274d6632058c135f701ea84dd5ab8ecc7@ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/d943poluenfqcb
    username: jdlysksngpmstg
    password: def7148466dd0f8b1bb5b50844542a7274d6632058c135f701ea84dd5ab8ecc7
    driver-class-name: org.postgresql.Driver
  ## Specify DBMS
  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.cmbassi.gestiondestock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

flickr:
  apiKey: da3d406c77a919c3f7b0d5f22f0fefb1
  apiSecret: 586bedcf752a71c8
  appKey: 72157720837293999-64c1ecc4e4e04542
  appSecret: bec0945d201abfa3
